Traceback (most recent call last):
  File "/home/users/wx83/GNN_baseline/GNN/train.py", line 72, in <module>
    NUM_FEAT = next(iter(train_loader)).x['note'].shape[1]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'x'
